#!/bin/tcsh
#
# Change directories to the top level dir of the Hyrax distribution.
# 'Source' this file to configure your c-shell shell to use operate Hyrax.

setenv prefix /usr/local/opendap/servers/hyrax-1.8.0
echo prefix: $prefix

setenv PATH $prefix/bin:$PATH
echo PATH: $PATH

setenv JAVA_HOME /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
echo JAVA_HOME: $JAVA_HOME

setenv JAVA_OPTS -Xmx1000m
echo JAVA_OPTS: $JAVA_OPTS

setenv CATALINA_HOME $prefix/apache-tomcat-6.0.33
echo CATALINA_HOME: $CATALINA_HOME


